2. Разметка главной страницы
htmlacademy-adaptive/832991-sedona-22 pull request #2
Opened 2021-03-31 07:41 UTC by foontomas

Выполнена разметка по БЭМ страницы index.html

2021-03-31 09:29 UTC, Manyaka requested changes

2021-03-31 09:29 UTC, Manyaka commented on source/index.html
> +    <link rel="stylesheet" href="css/style.css">
файла не существует. Раз ты его тут вызываешь - добавь хотя бы пустой

2021-03-31 09:29 UTC, Manyaka commented on source/index.html
> +          <img src="./img/logotype.svg" width="102" height="84" alt="логотип города Седона»">
файл отсутствует

2021-03-31 09:29 UTC, Manyaka commented on source/index.html
> +          <img src="./img/logotype.svg" width="102" height="84" alt="логотип города Седона»">
```suggestion
          <img src="./img/logotype.svg" width="102" height="84" alt="логотип города Седона.">
```
В альтах надо ставить точки на концах предложений, чтобы скрин ридер делал паузу

2021-03-31 09:29 UTC, Manyaka commented on source/index.html
> +    <div class="page__body-container">
Зачем этот див?

2021-03-31 09:29 UTC, Manyaka commented on source/index.html
> +          <div class="main-nav__wrapper">
див лишний, всё на ул вешаешь

2021-03-31 09:29 UTC, Manyaka commented on source/index.html
> +            </ul>
самостоятельный блок

2021-03-31 09:29 UTC, Manyaka commented on source/index.html
> +          <div class="main-nav__wrapper">
И нет смысла на все поля делать модификатор (мод) для мобильного вида, имеет смысл на ул повесить. И самое главное :) тк мобайл ферст, то мод должен быть у таблета и десктопа (а вообще лучше без мода сделать на брекпоинтах)

2021-03-31 09:29 UTC, Manyaka commented on source/index.html
> +                <a class="main-nav__link" href="#">
```suggestion
                <a class="main-nav__link">
```

мы на главной, хреф не надо

2021-03-31 09:29 UTC, Manyaka commented on source/index.html
> +                <a class="main-nav__link" href="#">
урл из тз добавь сюда

2021-03-31 09:29 UTC, Manyaka commented on source/index.html
> +            <!--Если учитывать, что у мокапа на баннере будет три версии и, соответственно три размера - то легче реализовать через множественный фон-->
тут picture будет, с размерами, не через цсс, а цсс можно буковки сделать, в смысле буквы - это свг, который можно через цсс добавить

2021-03-31 09:29 UTC, Manyaka commented on source/index.html
> +          <div class="advantages">
это всё ol

2021-03-31 09:29 UTC, Manyaka commented on source/index.html
> +          <div class="advantages">
8 пунктов, 3 мода: один с картинкой, один белый, один серый

2021-03-31 09:29 UTC, Manyaka commented on source/index.html
> +          <div class="map-search__title">
заголовок h2 у секции

2021-03-31 09:29 UTC, Manyaka commented on source/index.html
> +          <div class="map-search__title">
лишний див

2021-03-31 09:29 UTC, Manyaka commented on source/index.html
> +            <h3 class="map-search__h3">
а вот он и заголовок :) от секции h2

2021-03-31 09:29 UTC, Manyaka commented on source/index.html
> +            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d52385.135657476916!2d-111.83015810420495!3d34.85444381570011!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x872da13
### 
```suggestion
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d52385.135657476916!2d-111.83015810420495!3d34.85444381570011!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x872da132f942b00d%3A0x5548c523fa6c8efd!2z0KHQtdC00L7QvdCwLCDQkNGA0LjQt9C-0L3QsCA4NjMzNiwg0KHQqNCQ!5e0!3m2!1sru!2sru!4v1607865575919!5m2!1sru!2sru" width="320" height="350" frameborder="0" style="border: 0;" allowfullscreen="" aria-hidden="false" tabindex="0">
```

2021-03-31 09:29 UTC, Manyaka commented on source/index.html
> +          </form>
это ссылка на страницу со списком гостиниц (из html1 страница, тут такой нет, но предполагаем, что есть)

2021-03-31 09:29 UTC, Manyaka commented on source/index.html
> +        <div class="page-footer__contacts">
лишний див

2021-03-31 09:29 UTC, Manyaka commented on source/index.html
> +        <div class="page-footer__social social">
лишний див

2021-03-31 09:29 UTC, Manyaka commented on source/index.html
> +          </ul>
самостоятельный блок

2021-03-31 09:29 UTC, Manyaka commented on source/index.html
> +              <a class="social__link" href="https://twitter.com" aria-label="Блог в Twitter"><img src="./img/twitter.svg" alt="Twitter" width="17" height="17"></a>
свг не через img, а через svg

2021-03-31 09:29 UTC, Manyaka commented on source/index.html
> +          <span class="copyright__text">разработано</span>
это параграф

2021-03-31 13:28 UTC, foontomas commented on source/index.html
> +    <link href="https://fonts.googleapis.com/css?family=PT+Sans:400,700&amp;subset=latin,cyrillic" rel="stylesheet">
Сходил, добавил. В принципе, это временный пункт, есть критерий Б9, шрифты должны быть локальными

2021-03-31 13:32 UTC, foontomas commented on source/index.html
> +    <link rel="stylesheet" href="css/style.css">
Зная, что в следующем разделе будем его из блоков собирать, не стал добавлять. Поправил, есть пустой.

2021-03-31 14:54 UTC, foontomas commented on source/index.html
> +          <img src="./img/logotype.svg" width="102" height="84" alt="логотип города Седона»">
Добавил файл.

2021-03-31 14:57 UTC, foontomas commented on source/index.html
> +          <img src="./img/logotype.svg" width="102" height="84" alt="логотип города Седона»">
Расставил точки даже там, где отдельные слова (футер). В случае с восклицательными знаками в конце предложений как быть? Менять на точки или нет?

2021-03-31 15:05 UTC, Manyaka commented on source/index.html
> +          <img src="./img/logotype.svg" width="102" height="84" alt="логотип города Седона»">
не, не надо. Любой знак препинания - будет пауза

2021-03-31 15:06 UTC, foontomas commented on source/index.html
> +    <div class="page__body-container">
На нём висит внешняя тень у десктопного макета, да ширины для медиазапросов. В принципе, да, можно вместо него сделать page__body на <body> и перевесить всё на него.

2021-03-31 15:22 UTC, foontomas commented on source/index.html
> +          <div class="main-nav__wrapper">
Модификаторы пересмотрел, лишний див - убрал, он был действительно лишний

2021-04-01 08:56 UTC, foontomas commented on source/index.html
> +            <!--Если учитывать, что у мокапа на баннере будет три версии и, соответственно три размера - то легче реализовать через множественный фон-->
Теоретически мне про тег picture ещё не рассказали) Поэтому, здесь div c множественным фоном. Но я согласен, для фона picture идеально подойдёт.
Делал как-то так:
  width: 100%;
  height: 389px;
  background-color: @welcome-back;
  background-image: url("../img/welcome.svg"), url("../img/intro-triangle.svg"), url("../img/background-photo.jpg");
  background-size: 282px 214px, auto, cover;
  background-position: center 52%, 50% 100%, center 29%;
  position: relative;
  background-repeat: no-repeat, no-repeat;
Дальше - медиазапросами менял размеры. Правда, картинка грузилась изначально самая большая, что для раздела с адаптивной графикой - уже ошибка.

2021-04-01 08:56 UTC, foontomas commented on source/index.html
> +                <a class="main-nav__link" href="#">
сделал

2021-04-01 08:56 UTC, foontomas commented on source/index.html
> +                <a class="main-nav__link" href="#">
Сделал.

2021-04-01 15:29 UTC, foontomas commented on source/index.html
> +            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d52385.135657476916!2d-111.83015810420495!3d34.85444381570011!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x872da13
Вот тут не понял. Нужно пробел поставить после двоеточия или есть инлайновый стиль и нужно style="border: 0;" вынести в блок map-search?

2021-04-01 15:29 UTC, foontomas commented on source/index.html
> +          </form>
Ну это если не учитывать макет первой вёрстки, в которой на этом месте предполагается открывающаяся форма . А если приплести к этому интенсив js1, то можно додумать, что эта форма - фильтр, который будет отрисовывать метки на карте по данным, полученным с сервера. Короче, это я просто человек, измученный нарзаном. Открыл тз, вижу пункт, правлю.

2021-04-01 15:36 UTC, Manyaka commented on source/index.html
> +            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d52385.135657476916!2d-111.83015810420495!3d34.85444381570011!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x872da13
пробел

2021-04-02 06:02 UTC, Manyaka requested changes

2021-04-02 06:02 UTC, Manyaka commented on source/index.html
> +      <ul class="social-list">
![Снимок экрана 2021-04-02 в 09 00 44](https://user-images.githubusercontent.com/6417966/113385980-ef581400-9391-11eb-9e00-c1725e15ea3d.jpg)
поправь свегешки

2021-04-02 06:02 UTC, Manyaka commented on source/index.html
> +          <a class="social-list__link" social-list__link--last href="https://youtube.com" aria-label="Страница в Youtube">
что будешь вешать на мод last?

2021-04-02 12:06 UTC, foontomas commented on source/index.html
> +    <link rel="stylesheet" href="css/style.css">
А, я понял. У меня-то он есть, но в репу не попадает по причине наличия в гитигноре. Он же дальше будет собираться из less-блоков. Пока закомментил, в следующем задании будет нужен.

2021-04-02 12:07 UTC, foontomas commented on source/index.html
> +    <link rel="preconnect" href="https://fonts.gstatic.com">
Поменял сразу на woff2, файлы шрифтов закинул в /fonts

2021-04-02 12:07 UTC, foontomas commented on source/index.html
> +      <a class="page-header__logo">
Заменил на picture, там же два лого по факту.

2021-04-02 12:07 UTC, foontomas commented on source/index.html
> +          </li>
Не потерялось. Этот пустой блок нужен для выравнивания пунктов меню относительно макета. Если в него закидывать лого - родительский блок становится равным этому лого по высоте. Сделал так для того, чтобы меню не ломалось при расширении и изменении макетной ширины.

2021-04-02 12:07 UTC, foontomas commented on source/index.html
> +          <li class="nav-list__item nav-list__item--form">
Мод --logo скрывает пустой пункт для мобильного меню. На планшетной и десктопной ширинах - не работает. --form - банально выравнивает пункт меню по макету.

2021-04-02 12:07 UTC, foontomas commented on source/index.html
> +        <div class="main-nav__toggle-bar">
Это декоративный блок - панель с белым фоном для кнопки открытия меню в мобильной версии.
![toggle-bar](https://user-images.githubusercontent.com/30291317/113404256-8a5fe680-93b0-11eb-83f8-8928f0a93b18.jpg)

2021-04-02 12:07 UTC, foontomas commented on source/index.html
> +          </h3>
А я пробовал тут без br-ов. Это единственный случай во всём проекте, где они нужны. Если правильно помню, этот заголовок в мобильной версии по макету не выстраивается. Могу убрать, конечно, но потом, скорее всего, верну(

2021-04-02 12:07 UTC, foontomas commented on source/index.html
> +        <div class="intro__declare">
Это была обёртка для выравнивания содержимого. Удалил, попробую без дива.

2021-04-02 12:19 UTC, Manyaka commented on source/index.html
> +        <div class="main-nav__toggle-bar">
А, это хедер сам. А этот див лишний

2021-04-02 12:21 UTC, Manyaka commented on source/index.html
> +          </li>
если закинуть лого с позишн абсолют, то высоту ничто не затронет. Ты же всё равно сюда собираешь логотип положить

2021-04-02 12:25 UTC, Manyaka commented on source/index.html
> +          <li class="nav-list__item nav-list__item--form">
Добавишь тогда, когда будешь двигать, щас я пока не очень представляю зачем так делать, когда там все лишки выравниваются. У тебя получается 2 коротких лишки и 2 длинных. Не надо двигать одну форму, надо двигать симметрично.

2021-04-02 13:06 UTC, foontomas commented on source/index.html
> +          </li>
Я нашёл, откуда изначально растут ноги у этого отдельного лого. В ТЗ в первой вёрстке был пункт 3.2 "Логотип не является пунктом меню. Его нужно размечать отдельным элементом". Перенёс его в элемент списка меню, попробую так. Он в любом случае абсолютно спозиционирован.

2021-04-02 13:14 UTC, foontomas commented on source/index.html
> +          </li>
Хотя, погоди. Там не только пункт ТЗ. А как тогда быть с ситуацией, когда меню в мобильной версии меню открыто, пункт меню с лого скрывается? Если родительский блок display: none, его содержимое, даже если оно абсолютно спозиционировано всё равно не будет отображаться?

2021-04-02 13:21 UTC, foontomas commented on source/index.html
> +          </li>
Проверил, не отображается. Поэтому лого там отдельным элементом. Так что, если пустой элемент списка тебя не устраивает - надо убирать его, но лого в меню я положить не могу.

2021-04-05 13:43 UTC, Manyaka requested changes

2021-04-05 13:43 UTC, Manyaka commented on source/index.html
> +    <link rel="preload" href="fonts/ptsansbold.woff2" as="font" crossorigin="anonymous">
шрифты не так будут подключаться, убери это

2021-04-05 13:43 UTC, Manyaka commented on source/index.html
> +            <a class="page-header__logo">
```suggestion
            <a class="nav-list__logo">
```

2021-04-05 13:43 UTC, Manyaka commented on source/index.html
> +              <picture>
лишний тег, тут просто img

2021-04-05 13:43 UTC, Manyaka commented on source/index.html
> +                <source media="(min-width: 1200px)" srcset="img/logotype-desktop.svg">
этот соотв тоже не нужен

2021-04-05 13:43 UTC, Manyaka commented on source/img/logotype-desktop.svg
> +<svg width="187" height="97" viewBox="0 0 187 97" fill="none" xmlns="http://www.w3.org/2000/svg">
эта свг не нужна, все манипуляции по превращению свг логотипа из мобильного в таблет и десктоп будут происходить внутри одно и того же свг, путем добавления туда тега стайл

2021-04-05 13:43 UTC, Manyaka commented on source/index.html
> +                <img src="img/logotype.svg" width="102" height="84" alt="Логотип города Седона">
добавь точку в альт

2021-04-05 13:43 UTC, Manyaka commented on source/index.html
> +          <li class="nav-list__item nav-list__item--form">
не нужный модификатор

2021-04-05 13:43 UTC, Manyaka commented on source/index.html
> +        <div class="main-nav__toggle-bar">
лишний див

2021-04-05 13:43 UTC, Manyaka commented on source/index.html
> +        </div>
Я тут посмотрела на другие страницы, эта часть тоже в хедер входит, тк она там везде повторяется

2021-04-05 13:43 UTC, Manyaka commented on source/index.html
> +        </h3>
лишние бр

2021-04-05 13:43 UTC, Manyaka commented on source/index.html
> +        <ul class="advantages advantages--additional">
Модификатор лучше к голубым advantages добавить, тк их два, а серых три, кого больше - тот дефолт

2021-04-05 13:43 UTC, Manyaka commented on source/index.html
> +          </div>
див лишний

2021-04-05 13:43 UTC, Manyaka commented on source/index.html
> +                <img src="img/logotype.svg" width="102" height="84" alt="Логотип города Седона">
поправь везде

2021-04-05 13:43 UTC, Manyaka commented on source/index.html
> +              <img src="img/advantages/photo-city-mobile.jpg" srcset="img/advantages/photo-city-mobile@2x.jpg 2x" alt="город Седона" height="100%">
width еще надо задать, и не в процентах, хейт тоже поправь

2021-04-05 13:43 UTC, Manyaka commented on source/index.html
> +          <div class="advantages__image advantages__image--image-1">
мод не удачный, и у какой картинки будет мод, тебе тут тоже надо выбрать какое положение картинки будет дефолтным, а для какой потребуется модификатор

2021-04-05 13:43 UTC, Manyaka commented on source/index.html
> +            <img src="./img/advantages/icon-house.svg" width="75" height="72">
альт потерялся

2021-04-05 13:43 UTC, Manyaka commented on source/index.html
> +            <img src="./img/advantages/icon-house.svg" width="75" height="72">
поправить остальные

2021-04-05 13:43 UTC, Manyaka commented on source/index.html
> +          </div>
сделай один в один как первый блок

2021-04-05 13:43 UTC, Manyaka commented on source/index.html
> +        <ul class="advantages advantages--additional">
это не уровень блока advantages

2021-04-05 13:43 UTC, Manyaka commented on source/index.html
> +        <a href="https://htmlacademy.ru/intensive/htmlcss" target="_blank">
добавь сразу свегешку, она же у тебя есть уже.

2021-04-06 20:54 UTC, merged